### ISSUE TITLE
ch_PP-OCRv3_det_infer 从paddle转换为 pytorch报错

### ISSUE THREAD

**Issue by songchuanle-1** [frotms/PaddleOCR2Pytorch#66]
里边没有 ch_PP-OCRv3_det_infer推理模型中没有pdot文件等

W0210 16:42:27.085924 24096 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.6, Runtime API Version: 11.1
W0210 16:42:27.108862 24096 gpu_resources.cc:91] device: 0, cuDNN Version: 8.0.
Traceback (most recent call last):
  File "D:/software/app/pycharm_community/实验/PaddleOCR2Pytorch-main/test.py", line 10, in <module>
    a = paddle.fluid.load_dygraph('./model/ch_PP-OCRv3_det_infer')
  File "D:\software\app\Anaconda\iro\envs\d5\lib\site-packages\paddle\fluid\dygraph\checkpoint.py", line 283, in load_dygraph
    _dygraph_tracer().trace_op(
  File "D:\software\app\Anaconda\iro\envs\d5\lib\site-packages\paddle\fluid\dygraph\tracer.py", line 307, in trace_op
    self.trace(type, inputs, outputs, attrs,
ValueError: (InvalidArgument) Deserialize to tensor failed, maybe the loaded file is not a paddle model(expected file format: 0, but 1904018048 found).
  [Hint: Expected version == 0U, but received version:1904018048 != 0U:0.] (at ..\paddle\fluid\framework\lod_tensor.cc:276)
  [operator < load > error]

Process finished with exit code 1

**Comment by frotms** [comment]
@songchuanle-1 模型转换使用的是paddle的训练模型，不是推理模型
